// Generated by @nuxtjs/svg-sprite
export const sprites = {
  "ui": () => import("/Users/alexander/projects/me/portfolio_gallery/assets/sprite/gen/ui.svg").then(r => r.default || r)
}
export const spriteClass = "";

export const spriteClassPrefix = "";

export const defaultSprite = "icons";
